### PR TITLE
Change tutors & Remarks

### PR DESCRIPTION
**Pull request by ErinRuslan**
So I've added the change tutors function and also remarks related (add, edit or delete)
The sql also I changed a bit as I added a new table to hold all remarks made

### CODE REVIEW

**Comment by snorIax** [comment]
Thanks Erin! 
Merging this now

**Comment by snorIax** [comment]
Thanks Erin!
I'm trying to merge this with the main branch but for some reason, the changes you made do not include the additions I made to the student page. Basically, if I merge this, the student view page and its additions on the login and loginpage are gone. 

I think it's because you edited your code in the old codes which didn't include the student's view additions.

**Comment by snorIax** [comment]
Thanks Erin!
Merged

Can you check if the code works?

**Comment by ErinRuslan** [comment]
Yeah it works fine, thank you!!

**Pull request merged**
